# Generated by Django 2.0.2 on 2018-08-26 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=128)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
